# Config file for automatic testing at travis-ci.org

language: python

sudo: false

cache:
  directories:
    - ~/.cache/pip

matrix:
  include:
    - python: 3.6
      env: TOX_ENV=pep8
    - python: 3.6
      env: TOX_ENV=isort
    - python: 3.6
      env: TOX_ENV=py36
    - python: 3.7
      env: TOX_ENV=py37
  fast_finish: true

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements_test.txt

# command to run tests using coverage, e.g. python setup.py test
script: tox -e $TOX_ENV

after_success:
  - codecov -e TOX_ENV
